"""Convert Xevious WAV sounds to Mega Drive PCM4 format.

Each WAV -> 8-bit signed, 16 kHz mono, length padded to a multiple of 256
(the PCM4 driver requires 256-byte aligned address and length). Outputs one
.bin per sample plus src/megadrive/sounds_md.68k with .incbin hooks and the
md_sound_table indexed by sound ordinal.

Pure Python (no sox / no audioop): linear resampling done by hand.
"""
import os, wave, struct

this_dir = os.path.dirname(os.path.abspath(__file__))
snd_dir = os.path.join(this_dir, "..", "sounds")
out_dir = os.path.normpath(os.path.join(this_dir, "..", "..", "src", "megadrive"))

OUT_RATE = 16000

# ordinal -> (wav name, channel, volume 0-15, loop)
# channels: 0 = music / engine (mutually exclusive), 1-3 = SFX
# (mirrors src/amiga/sound_entries.68k channel + relative volume, /4 clamped)
SOUNDS = {
    0x01: ("main_theme",        0, 15, 1),
    0x02: ("highest_score",     0, 15, 0),
    0x03: ("high_score",        0, 15, 0),
    0x04: ("extra_solvalou",    3, 12, 0),
    0x05: ("flying_enemy_hit",  2, 10, 0),
    0x06: ("garu_zakato",       3,  8, 0),
    0x07: ("andor_genesis",     3,  9, 0),
    0x08: ("sheonite",          3,  9, 0),
    0x09: ("teleport",          2,  8, 0),
    0x0a: ("bacura_hit",        1,  9, 0),
    0x0b: ("shot",              1, 10, 0),
    0x0c: ("bomb",              1, 11, 0),
    0x0d: ("bonus_flag",        3,  9, 0),
    0x0e: ("solvalou",          0,  9, 1),
    0x10: ("coin",              1, 13, 0),
    0x11: ("ground_explosion",  3, 12, 0),
    0x12: ("solvalou_explosion",3, 14, 0),
}
MAX_ORD = 0x12

def read_wav_s8_16k(path):
    w = wave.open(path, "rb")
    nch, width, rate, n = (w.getnchannels(), w.getsampwidth(),
                           w.getframerate(), w.getnframes())
    raw = w.readframes(n)
    w.close()
    # decode to a list of mono float samples in [-1, 1)
    if width == 2:
        cnt = len(raw) // 2
        ints = struct.unpack("<%dh" % cnt, raw[:cnt * 2])
        if nch == 2:
            ints = [(ints[i] + ints[i + 1]) // 2 for i in range(0, len(ints) - 1, 2)]
        scale = 1.0 / 32768.0
    elif width == 1:
        cnt = len(raw)
        ints = [b - 128 for b in raw]
        if nch == 2:
            ints = [(ints[i] + ints[i + 1]) // 2 for i in range(0, len(ints) - 1, 2)]
        scale = 1.0 / 128.0
    else:
        raise ValueError("unsupported width %d" % width)

    # linear resample to OUT_RATE
    out_n = max(1, int(len(ints) * OUT_RATE / rate))
    out = bytearray(out_n)
    step = len(ints) / out_n
    pos = 0.0
    for i in range(out_n):
        idx = int(pos)
        frac = pos - idx
        a = ints[idx]
        b = ints[idx + 1] if idx + 1 < len(ints) else a
        v = (a + (b - a) * frac) * scale       # [-1, 1)
        s = int(round(v * 127))
        if s > 127: s = 127
        if s < -128: s = -128
        out[i] = s & 0xFF                       # signed 8-bit as byte
        pos += step
    # pad to a multiple of 256
    pad = (-len(out)) % 256
    out += bytes(pad)
    return bytes(out)

def main():
    table = {}      # ordinal -> (name, length, channel, vol, loop)
    for ordn, (name, ch, vol, loop) in SOUNDS.items():
        wav = os.path.join(snd_dir, name + ".wav")
        data = read_wav_s8_16k(wav)
        with open(os.path.join(out_dir, "smp_%s.bin" % name), "wb") as f:
            f.write(data)
        table[ordn] = (name, len(data), ch, vol, loop)
        print(f"0x{ordn:02x} {name}: {len(data)} bytes ({len(data)//256} blocks)")

    with open(os.path.join(out_dir, "sounds_md.68k"), "w") as f:
        f.write("* generated by assets/megadrive/convert_sounds_md.py - DO NOT EDIT\n\n")
        f.write("    .global md_sound_table\n    .global md_smp_base\n\n")
        f.write("    .section .rodata\n\n")
        # sound table: 8 bytes/entry indexed by ordinal 0..MAX_ORD
        #   long sample addr | word length>>8 | byte channel | byte vol<<4|loop
        f.write("    .align 2\nmd_sound_table:\n")
        for ordn in range(MAX_ORD + 1):
            if ordn in table:
                name, length, ch, vol, loop = table[ordn]
                f.write(f"    .long smp_{name}\n")
                f.write(f"    .word {length >> 8}\n")
                f.write(f"    .byte {ch}, {(vol << 4) | loop}   | 0x{ordn:02x} {name}\n")
            else:
                f.write(f"    .long 0\n    .word 0\n    .byte 0,0   | 0x{ordn:02x} (unused)\n")
        f.write("\nmd_smp_base:\n")
        for ordn, (name, *_rest) in sorted(table.items()):
            f.write(f"    .balign 256\nsmp_{name}:\n    .incbin \"smp_{name}.bin\"\n")

if __name__ == "__main__":
    main()
