"""Convert the Namco logo (assets/megadrive/Namco_logo.png) into the Sega 32X
boot-splash image.

A full-screen 320x224 8bpp image. The red wordmark is rendered as a 4-level
black->red ramp so the anti-aliased edges stay smooth; index 1 = opaque black
background, indices 2..4 = increasingly bright Namco red. The SH-2
(src/sega32x/src/main.c) blits it over the boot "load" screens for a few seconds,
then hands off to the game. The actual CRAM colours live in the SH-2 palette, so
the red can be tweaked there without regenerating this image.

Run once after changing the source logo:  py assets/megadrive/make_namco_logo.py
"""
import os
from PIL import Image

W, H = 320, 224
LOGO_W = 280              # wordmark width on the 320px screen (leaves a margin)
LEVELS = 4               # 1 = black, 2..4 = red ramp (matches load_namco_palette)
here = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(here, "Namco_logo.png")
out_dir = os.path.normpath(os.path.join(here, "..", "..", "src", "sega32x", "src"))


def main():
    im = Image.open(src).convert("RGBA")
    im = im.crop(im.split()[3].getbbox())          # trim transparent margins (alpha bbox)

    w, h = im.size
    nh = max(1, round(h * LOGO_W / w))
    im = im.resize((LOGO_W, nh), Image.LANCZOS)

    canvas = Image.new("RGB", (W, H), (0, 0, 0))
    canvas.paste(im, ((W - LOGO_W) // 2, (H - nh) // 2), im)   # composite over black via alpha

    red = canvas.split()[0].load()                 # red channel == logo coverage (red on black)
    out = bytearray(W * H)
    for y in range(H):
        for x in range(W):
            out[y * W + x] = (red[x, y] * LEVELS) // 256 + 1   # 1..LEVELS

    with open(os.path.join(out_dir, "gfx_namco_32x.bin"), "wb") as f:
        f.write(out)
    with open(os.path.join(out_dir, "gfx_namco_32x.s"), "w") as f:
        f.write("! generated by assets/megadrive/make_namco_logo.py - DO NOT EDIT\n"
                "! Namco boot-splash logo (320x224, 8bpp: 1=black bg, 2..4=red ramp)\n\n"
                "    .global _gfx_namco_32x\n\n"
                "    .section .rodata\n\n"
                "    .align 2\n"
                "_gfx_namco_32x:\n"
                '    .incbin "src/gfx_namco_32x.bin"\n')
    print("namco logo -> %s (wordmark %dx%d, %d bytes)"
          % (os.path.join(out_dir, "gfx_namco_32x.bin"), LOGO_W, nh, len(out)))


if __name__ == "__main__":
    main()
