"""Convert the Namco boot logo into Mega Drive tiles + nametable.

Reuses the 32X splash image (src/sega32x/src/gfx_namco_32x.bin, 320x224 8bpp,
1=black bg, 2..4=red ramp) so both targets share the same artwork. The MD shows
the logo through the window plane as a full-screen OPAQUE overlay (it has to hide
the booting game on planes A and B), so we keep the black background opaque:

    32X value 1 (black bg) -> MD pixel 1 (opaque black, PAL3 idx1)
    32X value 2..4 (red)   -> MD pixel 2..4 (red ramp, PAL3 idx2..4)

Outputs (src/megadrive/):
  gfx_namco_md_tiles.bin  deduplicated 4bpp tiles (32B each)
  gfx_namco_md_map.bin    40x28 nametable: raw tile index (asm adds base+PAL+pri)
  gfx_namco_md.68k        .incbin hooks + NAMCO_MD_NTILES equ

Run once after regenerating gfx_namco_32x.bin:  py assets/megadrive/make_namco_logo_md.py
"""
import os

W, H = 320, 224
COLS, ROWS = W // 8, H // 8                 # 40 x 28 tiles
here = os.path.dirname(os.path.abspath(__file__))
root = os.path.normpath(os.path.join(here, "..", ".."))
src = os.path.join(root, "src", "sega32x", "src", "gfx_namco_32x.bin")
out_dir = os.path.join(root, "src", "megadrive")


def main():
    with open(src, "rb") as f:
        img = f.read()
    assert len(img) == W * H, "unexpected namco image size %d" % len(img)

    # 32X values 1..4 map straight to MD pixels 1..4 (idx1 = opaque black bg)
    def px(v):
        return min(v, 4)

    tiles = []
    index = {}
    nmap = bytearray(COLS * ROWS * 2)

    for ty in range(ROWS):
        for tx in range(COLS):
            tile = bytearray(32)
            for r in range(8):
                base = (ty * 8 + r) * W + tx * 8
                for c in range(0, 8, 2):
                    hi = px(img[base + c])
                    lo = px(img[base + c + 1])
                    tile[r * 4 + c // 2] = (hi << 4) | lo
            tile = bytes(tile)
            ti = index.get(tile)
            if ti is None:
                ti = len(tiles)
                index[tile] = ti
                tiles.append(tile)
            cell = (ty * COLS + tx) * 2       # raw tile index; asm adds base/PAL/pri
            nmap[cell] = (ti >> 8) & 0xFF
            nmap[cell + 1] = ti & 0xFF

    with open(os.path.join(out_dir, "gfx_namco_md_tiles.bin"), "wb") as f:
        f.write(b"".join(tiles))
    with open(os.path.join(out_dir, "gfx_namco_md_map.bin"), "wb") as f:
        f.write(nmap)
    with open(os.path.join(out_dir, "gfx_namco_md.68k"), "w") as f:
        f.write("* generated by assets/megadrive/make_namco_logo_md.py - DO NOT EDIT\n")
        f.write("* Namco boot logo: %d unique 4bpp tiles + 40x28 raw-index nametable\n\n"
                % len(tiles))
        f.write("    .equ NAMCO_MD_NTILES, %d\n\n" % len(tiles))
        f.write("gfx_namco_md_tiles:\n    .incbin \"gfx_namco_md_tiles.bin\"\n\n")
        f.write("gfx_namco_md_map:\n    .incbin \"gfx_namco_md_map.bin\"\n")

    print("namco MD logo -> %d unique tiles (%d bytes), %dx%d map"
          % (len(tiles), len(tiles) * 32, COLS, ROWS))


if __name__ == "__main__":
    main()
