! generated by assets/megadrive/make_namco_logo.py - DO NOT EDIT
! Namco boot-splash logo (320x224, 8bpp: 1=black bg, 2..4=red ramp)

    .global _gfx_namco_32x

    .section .rodata

    .align 2
_gfx_namco_32x:
    .incbin "src/gfx_namco_32x.bin"
