! generated by assets/megadrive/convert_graphics_md.py - DO NOT EDIT
! 128 arcade colours, 695 sprite frames (8bpp, numbered by MD frame id)

    .global _gfx_32x_palette
    .global _gfx_32x_sprites
    .global _gfx_32x_nframes

    .section .rodata

    .align 2
_gfx_32x_palette:
    .incbin "src/gfx_32x_palette.bin"

    .align 2
_gfx_32x_sprites:
    .incbin "src/gfx_32x_sprites.bin"

    .align 2
_gfx_32x_nframes:
    .long 695
