! generated by assets/megadrive/convert_graphics_md.py - DO NOT EDIT

    .global _gfx_egg_32x
    .global _gfx_egg_32x_pal

    .section .rodata

    .balign 4
_gfx_egg_32x:
    .incbin "src/gfx_egg_32x.bin"

    .align 2
_gfx_egg_32x_pal:
    .incbin "src/gfx_egg_32x_pal.bin"
