/*
 * Xevious 32X - slave SH-2: 4-channel PCM mixer over PWM.
 *
 * The 68000 sends sound commands through COMM4 (high byte = opcode, low byte =
 * sound ordinal): 1 = play, 2 = stop, 3 = mute, 4 = unmute. We look the ordinal
 * up in snd_tbl (generated by convert_sounds_md.py), set up its channel, and
 * mix the active channels into the PWM FIFO every sample. Channels: 0 = music/
 * engine, 1-3 = SFX. Samples are 8-bit signed, 16 kHz.
 *
 * PWM init follows d32xr (see the sega-32x-slave-and-pwm notes). The slave does
 * sound only, so a polling loop (no interrupt) keeps the FIFO fed.
 */
#include "types.h"
#include "32x.h"

typedef struct {
    unsigned int  off;        /* offset into snd_data */
    unsigned int  len;        /* sample length in bytes */
    unsigned char ch, vol, loop, pad;
} snd_ent;

extern const snd_ent     snd_tbl[];
extern const signed char snd_data[];

#define PWM_CYCLE  1439
#define PWM_CENTER (PWM_CYCLE / 2)

static struct {
    const signed char *ptr;
    int rem;
    const signed char *start;
    int len;
    int vol;
    int loop;
} chan[4];

static int snd_mute;

static void snd_cmd(unsigned short c)
{
    int op  = c >> 8;
    int arg = c & 0xFF;
    int ci;
    const snd_ent *e;

    switch (op)
    {
    case 1:                                       /* play ordinal */
        e = &snd_tbl[arg];
        if (e->len == 0) break;
        ci = e->ch & 3;
        chan[ci].start = snd_data + e->off;
        chan[ci].ptr   = chan[ci].start;
        chan[ci].len   = e->len;
        chan[ci].rem   = e->len;
        chan[ci].vol   = e->vol;
        chan[ci].loop  = e->loop;
        break;
    case 2:                                       /* stop ordinal -> stop channel */
        ci = snd_tbl[arg].ch & 3;
        chan[ci].rem  = 0;
        chan[ci].loop = 0;
        break;
    case 3: snd_mute = 1; break;
    case 4: snd_mute = 0; break;
    }
}

void slave(void)
{
    int i;
    for (i = 0; i < 4; i++) chan[i].rem = 0;

    MARS_PWM_MONO = 1;                            /* prime FIFO */
    MARS_PWM_MONO = 1;
    MARS_PWM_MONO = 1;
    MARS_PWM_CYCLE = PWM_CYCLE;
    MARS_PWM_CTRL  = 0x0185;                      /* TM=1, RTP, R=right, L=left */

    while (1)
    {
        unsigned short c;
        int sum, pulse;

        while (MARS_PWM_MONO & 0x8000) ;          /* wait for FIFO space */

        c = MARS_SYS_COMM4;
        if (c) { snd_cmd(c); MARS_SYS_COMM4 = 0; }

        sum = 0;
        for (i = 0; i < 4; i++)
        {
            if (chan[i].rem > 0)
            {
                sum += ((int)(*chan[i].ptr) * chan[i].vol) >> 3;  /* gain: use more PWM range */
                chan[i].ptr++;
                if (--chan[i].rem == 0 && chan[i].loop)
                {
                    chan[i].ptr = chan[i].start;
                    chan[i].rem = chan[i].len;
                }
            }
        }
        if (snd_mute) sum = 0;

        pulse = PWM_CENTER + sum;
        if (pulse < 1) pulse = 1;
        else if (pulse > PWM_CYCLE - 1) pulse = PWM_CYCLE - 1;
        MARS_PWM_MONO = pulse;
    }
}
