! generated by assets/megadrive/convert_sounds_md.py - DO NOT EDIT

    .global _snd_tbl
    .global _snd_data

    .section .rodata

    .align 2
_snd_tbl:
    .long 0, 0
    .byte 0, 0, 0, 0
    .long 0, 101632
    .byte 0, 15, 1, 0   ! 0x01 main_theme
    .long 101632, 84992
    .byte 0, 15, 0, 0   ! 0x02 highest_score
    .long 186624, 101632
    .byte 0, 15, 0, 0   ! 0x03 high_score
    .long 288256, 15104
    .byte 3, 12, 0, 0   ! 0x04 extra_solvalou
    .long 303360, 3328
    .byte 2, 10, 0, 0   ! 0x05 flying_enemy_hit
    .long 306688, 6400
    .byte 3, 8, 0, 0   ! 0x06 garu_zakato
    .long 313088, 28416
    .byte 3, 9, 0, 0   ! 0x07 andor_genesis
    .long 341504, 20224
    .byte 3, 9, 0, 0   ! 0x08 sheonite
    .long 361728, 1792
    .byte 2, 8, 0, 0   ! 0x09 teleport
    .long 363520, 2560
    .byte 1, 9, 0, 0   ! 0x0a bacura_hit
    .long 366080, 1280
    .byte 1, 10, 0, 0   ! 0x0b shot
    .long 367360, 12032
    .byte 1, 11, 0, 0   ! 0x0c bomb
    .long 379392, 9728
    .byte 3, 9, 0, 0   ! 0x0d bonus_flag
    .long 389120, 50944
    .byte 0, 9, 1, 0   ! 0x0e solvalou
    .long 0, 0
    .byte 0, 0, 0, 0
    .long 440064, 8704
    .byte 1, 13, 0, 0   ! 0x10 coin
    .long 448768, 15360
    .byte 3, 12, 0, 0   ! 0x11 ground_explosion
    .long 464128, 28928
    .byte 3, 14, 0, 0   ! 0x12 solvalou_explosion
    .long 493056, 66048
    .byte 0, 15, 0, 0   ! 0x13 cheteiro

    .balign 2
_snd_data:
    .incbin "src/snd_32x.bin"
